language: php

php:
- 7.0
- 7.1

services:
- mysql

before_script:
- cp .env.travis .env
- mysql -e 'create database testing;'
- composer self-update
- composer install --no-interaction
- php artisan key:generate
- php artisan migrate --seed

script:
    - vendor/bin/phpunit

notifications:
email:
    recipients:
        - christ.heaven22@gmail.com
    on_success: always
    on_failure: always
